[build-system]
requires = ["uv_build>=0.12.4,<0.13"]
build-backend = "uv_build"

[project]
name = "pydal-limbo"
description = "Custom pyDAL adapter for limbo (SQLite rebuild)"
readme = "README.md"
requires-python = ">=3.10"
license-expression = "MIT"
authors = [
    {name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl"}
]
urls = { "Homepage" = "https://github.com/robinvandernoord/pydal-adapter-limbo" }

dependencies = [
    "pydal",
    "pylimbo",
]
version = "0.1.1"

[tool.uv.build-backend]
module-root = ""

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = []

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
feat = "minor"
fix = "patch"
perf = "patch"
